# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/budget',
                'doc_host': 'https://jairuspace.github.io',
                'git_url': 'https://github.com/jairuspace/budget',
                'lib_path': 'budget'},
  'syms': {'budget.core': {'budget.core.foo': ('core.html#foo', 'budget/core.py')}}}
